#!/bin/bash
set -eo pipefail
IFS=$'\n\t'

sandbox () {
  
  # Enter attaches users to a shell in the desired container
  enter () {
    case $2 in
      influxdb)
        echo "Entering /bin/bash session in the influxdb container..."
        docker-compose exec influxdb /bin/bash
        ;;
      chronograf)
        echo "Entering /bin/sh session in the chronograf container..."
        docker-compose exec chronograf /bin/sh
        ;;
      kapacitor)
        echo "Entering /bin/bash session in the kapacitor container..."
        docker-compose exec kapacitor /bin/bash
        ;;
      telegraf)
        echo "Entering /bin/bash session in the telegraf container..."
        docker-compose exec telegraf /bin/bash
        ;;
      *)
        echo "sandbox enter (influxdb||chronograf||kapacitor||telegraf)"
        ;;
    esac
  }
  
  # Logs streams the logs from the container to the shell
  logs () {
    case $2 in
      influxdb)
        echo "Following the logs from the influxdb container..."
        docker-compose logs -f influxdb
        ;;
      chronograf)
        echo "Following the logs from the chronograf container..."
        docker-compose logs -f chronograf
        ;;
      kapacitor)
        echo "Following the logs from the kapacitor container..."
        docker-compose logs -f kapacitor
        ;;
      telegraf)
        echo "Following the logs from the telegraf container..."
        docker-compose logs -f telegraf
        ;;
      *)
        echo "sandbox logs (influxdb||chronograf||kapacitor||telegraf)"
        ;;
    esac
  }

  case $1 in
    up)
      echo "Spinning up Docker Images..."
      echo "If this is your first time starting sandbox this might take a minute..."
      docker-compose up -d
      echo "Opening tabs in browser..."
      sleep 3
      if [ $(uname) == "Darwin" ]; then
        open http://localhost:3000
        open http://localhost:8888
      elif [ $(uname) == "Linux" ]; then
        sensible-browser http://localhost:8888
        sensible-browser http://localhost:3000
      else
        echo "no browser detected..."
      fi
      ;;
    down)
      echo "Stopping and removing running containers..."
      docker-compose down
      ;;
    restart)
      echo "Stopping all processes..."
      docker-compose down > /dev/null 2>&1
      echo "Starting all processes..."
      docker-compose up -d > /dev/null 2>&1
      echo "Services available!"
      ;;
    delete-data)
      echo "deleting all influxdb, kapacitor and chronograf data..."
      rm -rf kapacitor/data influxdb/data chronograf/data
      ;;
    docker-clean)
      echo "Stopping all running containers..."
      docker stop $(docker ps -a -q) > /dev/null 2>&1
      echo "Removing all containers..."
      docker rm $(docker ps -a -q) > /dev/null 2>&1
      echo "Removing TICK images..."
      docker rmi sandbox_documentation influxdb:1.2.2 telegraf:1.2.1 kapacitor:1.2.0 quay.io/influxdb/chronograf:1.2.0-beta7 > /dev/null 2>&1
      ;;
    influxdb)
      echo "Entering the influx cli..."
      docker-compose exec influxdb /usr/bin/influx
      ;;
    rebuild-docs)
      echo "Rebuilding documentation container..."
      docker build -t sandbox_documentation documentation/ > /dev/null 2>&1
      echo "Restarting..."
      docker-compose down > /dev/null 2>&1
      docker-compose up -d > /dev/null 2>&1
      ;;
    enter)
      enter $@
      ;;
    logs)
      logs $@
      ;;
    *)
      cat <<-EOF
sandbox commands:
  up           -> spin up the sandbox environment
  down         -> tear down the sandbox environment
  restart      -> restart the sandbox
  influxdb     -> attach to the influx cli
  
  enter (influxdb||kapacitor||chronograf||telegraf) -> enter the specified container
  logs  (influxdb||kapacitor||chronograf||telegraf) -> stream logs for the specified container
  
  delete-data  -> delete all data created by the TICK Stack 
  docker-clean -> stop and remove all running docker containers and images
  rebuild-docs -> rebuild the documentation image
EOF
      ;;
  esac
}

sandbox $@
